services:
  api: 
    image: natalie2201/fastapi-test:latest
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]
    ports:
      - 3000:3000
    depends_on:
      - bdd
    volumes:
      - ./app:/code/app
  bdd:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calories
    ports:
      - 5432:5432
    volumes:
      - ./database-calories:/var/lib/postgresql/data