services:
  watchtower:
    image: nickfedor/watchtower:latest # this one works with ARM64
    platform: linux/amd64 
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 <em># Poll every 60 seconds</em>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
  api: 
    image: natalie2201/fastapi-test:latest
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]
    ports:
      - 3000:3000
    depends_on:
      - bdd
    volumes:
      - ./app:/code/app
  bdd:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calories
    ports:
      - 5432:5432
    volumes:
      - ./database-calories:/var/lib/postgresql/data